### ISSUE TITLE
Maximum image size is only 16 MB when use `mksfs zip`

### ISSUE THREAD

**Issue by equation314** [wangrunji0408/rcore-fs#4]
https://github.com/wangrunji0408/rcore-fs/blob/48b3c2618a9589490a2b327844740a9fe1950b11/src/bin/mksfs.rs#L26

**Comment by wangrunji0408** [comment]
GG. Sorry for the casual hard code.

**Comment by wangrunji0408** [comment]
fixed in 65cf693
